### ISSUE TITLE
Block In  SharpPcap.LibPcap.CaptureFileWriterDevice constructor when run in dotnetcore2.2 Arm64

### ISSUE THREAD

**Issue by jiaweipray** [chmorgan/sharppcap#109]
HI:
     We use sharppcap 5.0.0 ,dotnetcore 2.2 in my code and  publish a target run in arm64 platform. The code block in SharpPcap.LibPcap.CaptureFileWriterDevice constructor a long time.  All is working well in windows10 64 bit os  ,centos7 64bit os,but it block in the arm64 platform.

**Comment by chmorgan** [comment]
Hi @jiaweipray. You'll have to be more specific about where you are seeing it hang. Are you sure it isn't due to the .net runtime loading system libraries into memory, or the time it takes to find and open the file for writing on your system? We would need more profiling info to know what the issue might be. You should look at the code for CaptureFileWriterDevice, I think you'll find it isn't doing a ton of stuff that should cause any appreciable amount of delay beyond what is expected of filesystem io, but I'd be interested in what you think.

**Comment by chmorgan** [comment]
Closing due to lack of response from OP.
