### ISSUE TITLE
How to distinguish between TCP data and UDP?

### ISSUE THREAD

**Issue by bbhxwl** [chmorgan/sharppcap#113]
How to distinguish between TCP data and UDP?
TCP is OK, but UDP doesn't seem to work.

             var udppPacket = packet.Extract<PacketDotNet.UdpPacket>();
if (udppPacket != null)

**Comment by bbhxwl** [comment]
I know the point. How can I distinguish between received and sent data?

**Comment by kayoub5** [comment]
@bbhxwl Sadly the libpcap API itself does not offer the possibility to get the per packet direction. however some workarounds exist:
* If you are not sending traffic yourself, you can check the MAC Address source of the packet is not the same as the adapter MAC Address
* If you just to filter only received traffic (eliminate traffic you send yourself) you could use `OpenFlags.NoCaptureLocal`

**Comment by chmorgan** [comment]
Hi @bbhxwl. I'm going to close this one out. @kayoub5 mentioned the NoCaptureLocal option, another is to use a bpf to filter out packets that match the local Mac address in the sender field. A third and less performant option is to filter in c# after receiving each packet. I'd probably start with the flag, then in c# due to simplicity and then if that isn't fast enough use a filter approach.
