### ISSUE TITLE
Writing to capture file does not create the same file as Wireshark

### ISSUE THREAD

**Issue by twa89** [chmorgan/sharppcap#115]
I started using sharppcap last year when Wireshark was using winpcap still and files created by using 
captureFileWriter.Write(e.Packet) would create the same file format that wireshark does.  Now that its using npCap the files are not the same.   I would like to be able to open files written by sharppcap  again in Wireshark and see the same level of parsing.  Wireshark doesn't seem to recognize what is written.  It only shows ethernet addresses and data bytes.  Is this a known problem?  Thanks for any assistance.

**Comment by chmorgan** [comment]
Hi @twa89, what version of npcap are you using? What version of Wireshark? I believe newer versions of wireshark are using the new pcap format and npcap should be as well but I'm also out of the loop on what might have changed there.

**Comment by twa89** [comment]
The very latest version of both.  Wireshark 3.2.3 and npCap .9989.  It all worked fine with winpCap.

**Comment by twa89** [comment]
i debugged this and I found the problem only occurs when I used the Npcap loopback adapter.  If I use a regular NIC then the packets are written correctly.  I believe this defect is therefore in the Npcap components.

**Comment by kayoub5** [comment]
@twa89 I think I know what your problem is:
* `new CaptureFileWriterDevice(captureFilename)` uses link layer Ethernet by default
* Loopback adapters uses link layer Null

The simple solution would be to use `new CaptureFileWriterDevice(device, captureFilename)` or any CaptureFileWriterDevice constructor that takes a `PacketDotNet.LinkLayers` as argument.
