### ISSUE TITLE
Long waiting for next version nuget

### ISSUE THREAD

**Issue by trudyhood** [chmorgan/sharppcap#178]
Sorry, I couldn't find your discussion link so I open an issue here,

We've created a VPN solution heavily based on SharpPcap here:
https://github.com/vpnhood/VpnHood

We are waiting for the next release of SharpPcap nuget with the latest version of WinDivert, but nuget version 5.3 does not have the latest version on your repository we needed. Would you let me know when do you plan to release it? Or is is possible to release the next version sooner :)

**Comment by chmorgan** [comment]
Hello @trudyhood. Oh I see now that 5.3.0 doesn't have the Windivert changes.

This is a great time to msg as I've got a bit of time due to the holidays. Let me get 5.4.0 out in the near future for you, sorry for the delay.

Have you been able to test the WinDivert support in the GitHub version to confirm it works as expected? Now would be a better time to confirm that than after 5.4.0 was pushed out :-)

**Comment by trudyhood** [comment]
Thank you for replying @chmorgan ,

We have been running the project with the Github version for about two months as there is no issue reported yet. It is satisfied with our needs; the only problem is the Nuget. Our solution offers NuGet based component at it is essential for us to use SharpPcap NuGet as a dependency rather than our compiled version.

**Comment by chmorgan** [comment]
Hi @trudyhood. I'm waiting to see if https://github.com/chmorgan/sharppcap/issues/177 is something we can fix before the next release. If I don't get a response in a day or so we'll push out the next rev and fix it with another release. Sorry for the delay.

**Comment by chmorgan** [comment]
5.4.0 was just pushed out to nuget.
