### ISSUE TITLE
AccessViolationException on MarshalRawPacket

### ISSUE THREAD

**Issue by KoenPlasmansLS** [chmorgan/sharppcap#295]
Runtime system: Windows (client installation so not much known and unable to reproduce on developer machine)
Installed software: SharpPcap 5.4.0
Application uses .NET Version 4.8

We came across several of our customers running different windows environments, having the following issue that is being logged in our software. Seems like memory access issue with pointers but I'm not and expert. Even though it looks like a duplicate of https://github.com/chmorgan/sharppcap/issues/290, the originating code where it occurs is quite different. Note that I was not able to reproduce as it works for 99,99% of the cases. Any clue as to what could be going wrong?

Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
at System.Runtime.InteropServices.Marshal.CopyToManaged(IntPtr, System.Object, Int32, Int32)
at SharpPcap.LibPcap.PcapDevice.MarshalRawPacket(IntPtr, IntPtr)
at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr, IntPtr, IntPtr)
at SharpPcap.LibPcap.Windows.pcap_dispatch(IntPtr, Int32, pcap_handler, IntPtr)
at SharpPcap.LibPcap.PcapDevice.CaptureThread(System.Threading.CancellationToken)
at SharpPcap.LibPcap.PcapDevice+<>c_DisplayClass79_0.<StartCapture>b_0()

**Comment by kayoub5** [comment]
* OS used?
* Is the application multi threaded?
* Does the application close the device while it's receiving packets in `OnPackerArrival` ?

**Comment by KoenPlasmansLS** [comment]
- Various Windows OS, if I have to name one Windows Server 2019
- Yes
- The code that closes the device will first deregister the OnPacketArrival delegate: 
         device.OnPacketArrival -= Device_OnPacketArrival;
         device.Close();

**Comment by kayoub5** [comment]
PcapDevice is not thread safe (since `pcap_t` in WinPcap/Libpcap/Npcap is not thread safe), meaning if more than one thread access it at the same time, AccessViolationException will happen.
Most common case is device.Close() being called while OnPacketArrival is being called, or about to be called.
Example Sequence:
* Thread A: calls PacketHandler from pcap_dispatch
* Thread B: calls device.Close() 
* Thread A: calls MarshalRawPacket, the pointer to the data is no longer valid since the device was closed.
* Thread A: AccessViolationException

**Comment by KoenPlasmansLS** [comment]
I'm going to assign an engineer on this issue if that is indeed the case and we'll come back to you as soon as possible. Thanks for looking into this and for coming up with a possible cause.

**Comment by kayoub5** [comment]
@KoenPlasmansLS any luck with isolating the issue?
