### ISSUE TITLE
.NET Core 2.0 on Linux: Unable to load DLL 'wpcap'

### ISSUE THREAD

**Issue by AlexanderHermann** [chmorgan/sharppcap#42]
Hi,
I have created a basic .NET Core 2.0 application using the VS template for a ".NET Core ASP.NET Core Web Application".
### Code
```
using System;
using SharpPcap.LibPcap;

namespace SharpTest
{
    class Program
    {
        static void Main()
        {
            // Retrieve the device list
            var devices = LibPcapLiveDeviceList.Instance;

            // Print out the devices
            int i = 0;
            foreach (var dev in devices)
            {
                /* Description */
                Console.WriteLine("Device {0}: {1} | {2}", i, dev.Name, dev.Description);
                i++;
            }

            Console.ReadLine();
        }
    }
}
```
### Dependencies
(from current sharppcap revision 4.5.0)
- PacketDotNet.dll
- SharpPcap.dll
### Target Framework
.NET Core 2.0 (added "netcoreapp2.0" for the "TargetFramework" property in the .csproj-file)
### Steps (Linux Ubuntu 16.04)
Copied to Linux, started with: $ dotnet SharpTest.dll
### Error 
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'wpcap': The specified module or one of its dependencies could not be found.
(Exception from HRESULT: 0x8007007E)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_findalldevs(IntPtr& alldevs, StringBuilder errbuf)
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.GetDevices()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.Refresh()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList..ctor()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.get_Instance()
   at SharpTest.Program.Main() in C:\Users\Username\source\repos\SharpTest\SharpTest\Program.cs:line 11

**Comment by oldsqlwnb** [comment]
The message says that you need to install the WinPcap driver [https://www.winpcap.org/install/default.htm](url). But since you are working on Linux I have no Idea how one would go about it. Maybe try extracting the wcap.dll from the WinPcap driver and reference it directly into your project.

**Comment by chmorgan** [comment]
@oldsqlwnb the issue is a bit deeper than that. I'll probably end up implementing dynamic library loading to resolve it. If you run under mono then the SharpPcap.dll.config file's dllmap will take effect and let you map wpcap to libpcap. So the fix is to run under mono for now and ensure the dllmap is correct for the name of libpcap on your system. I'm hoping to have a better fix that is dotnet compatible but it does require a bit of code to dynamically load dlls based on platform etc.

**Comment by AlexanderHermann** [comment]
@chmorgan Thanks for the clarification. Since my goal is to abstain from Mono and rely solely on .NET Core, I guess I will have to wait for the prospective solution of dynamically loading DLLs based on the platform.

**Comment by chmorgan** [comment]
Hi Alexander.

This is a known limitation of the library. You could run your application
under mono with a .config file that does a dllmap to libpcap if you’d like
a short term work around.

**Comment by los93sol** [comment]
An alternative that I used was to just drop the lip cap dll so it is published with the project and hard coded it to look for my dll.

@chmorgan, instead of trying to get fancy with some dynamic loader why not just have the caller pass in what they want to use?

**Comment by chmorgan** [comment]
How would that look/work in terms of api? Right now the dll is specified at
compile time. Is it possible to pass that in and use the same binding
mechanism?

**Comment by los93sol** [comment]
I can’t say for certain about WinPcap, but for libpcap on Linux I didn’t have to install it, I just dropped the dll in the project bin folder and that works as expected.  I’m not sure about licensing but it seems like you could split the NuGet packages so you could publish SharpPCap, WinPCap (that just contains the dll), and LibPCap (again just containing the dll).  That would give you the ability to control the naming and guarantee the file exists in the bin which also helps ease deployment of apps using SharpPCap since you don’t need to make sure one or the other is present on the target machine.  Just another idea to skin it.

**Comment by winkmichael** [comment]
Include SharpPcap.dll.config in the runtime directory next to SharpPCap.dll


<configuration>
  <dllmap dll="wpcap" target="libpcap.so.0.8" os="linux" />
  <dllmap dll="wpcap" target="libpcap.dylib"  os="osx"   />
</configuration>

**Comment by lukasvosyka** [comment]
Maybe this is being solved soon from the coreclr team..

https://github.com/dotnet/corefx/issues/32015

**Comment by chmorgan** [comment]
@lukasvosyka yep, that is the new ticket to track that issue. When there is a dotnet solution I'll be applying that to sharppcap to resolve the issue.

**Comment by AlexanderHermann** [comment]
That's great news, thanks for the update!

**Comment by chmorgan** [comment]
@epasinetti it sounds like the issue is still winding through the dotnet process. I'm getting some updates from the above ticket below but its been quiet for a week. If you are watching the above link to the api ticket I'd be interested when they get that into a usable form. At that point we'll want to get a PR in to support it and finally get proper dotnet support.

**Comment by fukaminakrize** [comment]
Hi @epasinetti, as a workaround to get sharppcap working on Linux using .net core, I've setup libwpcap.so link file pointing to installed libpcap.so (_ln -s /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 /usr/lib/x86_64-linux-gnu/libwpcap.so_).

**Comment by chmorgan** [comment]
Hi @fukaminakrize, @AlexanderHermann, please check out the 4.6.0 release, it should address the cross platform issues with dotnet.

**Comment by AlexanderHermann** [comment]
Hi @chmorgan, glad to hear the issue was addressed, thanks for the heads up!

**Comment by bbhxwl** [comment]
I haven't solved it yet. I don't know why. I use the latest version.

**Comment by Humberto-Molina** [comment]
is there a solution to this? I have the same problem

**Comment by kayoub5** [comment]
@Humberto-Molina please open a separate ticket with details on your specific context.
