### ISSUE TITLE
Automatically chose default device

### ISSUE THREAD

**Issue by Rookian** [chmorgan/sharppcap#84]
In your given examples I have to manually select a device I want to capture. 
Is there any possibility to automatically chose the default device? 
How do other sniffing tools (like snapy) automatically chose the right device?

**Comment by kayoub5** [comment]
@Rookian most tools pick the `any` interface if exists, otherwise use the first available interface.
Some extra checks are sometimes added to pick the first operational interface (ignore interfaces that are not connected to anything).
See https://github.com/chmorgan/sharppcap/blob/master/Test/TestHelper.cs#L29 for how such logic would look like.

**Comment by Rookian** [comment]
@kayoub5 I used the win32 api GetBestInterface. See https://github.com/Rookian/War3Stats/blob/451aa762efefd8ccd4b7d10cd8b227c8b4dfe184/WC3Stats/NIC.cs#L15
